language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: WQFpUB1kqC33B/vL2zFv3RXKggZQj1mPof4MO/mPxxanWwrwGMitQe1P7FYeaMMAvzHZiS/K0T6H2z5xYRXr+mD0W3Vna9tDam0iGkICUsesmVpyPmynKBWfa5wdNeJsJRNbdCPHr+D1o7+gY8aVZtr8Y7+muMkl9fsmFFJp/kSXT8LXu+7AwRo0BcCq9nAfFgiCcLuRERlDYyAmJjjvxakCwYDY9LiUp9iKN6A7u4uSI+AadFOSumiAMjmIVy1ztfi+FFEXGoMVL9FB1AWhYlssT1Uh6cp5fChd+8Ca0uXe+pxbCPGlfusGD9ItnGr0/ogroISiRh0rtARREjP/P+jX+MM3szr2SEAeWoO5egkin4KVSL7fdcnf+my9GAcD3B44ET0x8MJwyp++iuYwswYNS9liifWAI8GsfiN4tX273eNiRcQCBklFNc1osmmPf/Qvm/X+Spf0Z6yBkl9UPcWhwg7+lgm3hqV7TEkJdkqc4X5ZkQ/6rdzv9uugpx3qcABs2gwPB0iRyJoimjiCzguILV/4WUzo5bSdsiNi+OtsZAYW1Sn3jSfeahaBwkTpLNWIKjaU4uB6zpBf5xmVtgfjljtFriS2YI2iCZ11J0j6JSuz/XDTF5fS5xXCCfeaUIVcpZLFFJJ9UnDSbkywHLk/1AofByQd6aoeEgJPJJk=
  app: rocky-headland-29162
  on:
    repo: fishtailwrinkle/node-shopping-list-integration-tests
