language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: jhe94TO2Sr6xzcHl/e01XrBSMYQBvABGzBVF+LImiZj0z6DWo5xjxK9DTlVTYg7IOQ1vTnVeNdnZ0Xw1WT1BQ0aCImGaoqAeI7L7IML9Yrj9kiM+YVlZBmA5C4reUc98Xti3zcSn8DxaAli3Jqt9MN4Qzn4ti+Amk+FXpvBt7P0lQUEK5TWOIqJkWk1gmz+3kVUZdJKsKgI5vuKs4kX75nO0rt82k6hNgDkRjuVq0ZTOgCtnlLPglBQykQffgFliz8wlsrweHqxy4QhTDVBzE1fgPkUS7DoGM7Rtikh++SxoaKst2tAy5UYvR539wy9+U6dluKAZ/NtpcW31wgROlNdwAnPMU2zra3bGyl8Rv7lgMJVbZErG8jLyicgO/lD/Quw3lbcu6WVR4FjmqAEsuiLjes9syM9tyYyhhyNrfRfK7PcLYds2f4cZFZWRMZJTOYezNlsEv6MLeVorFENGG4xpVB73BleDl7eqDFawejy2HZTaPlD06TSzdM9udY1VGK1IefRq2nogDYmh3Gmz5WOdxJU815J+Kqxc3/8gvYDOle3hSK+TVIKtGDHF0i5C6O9bmI3+Ggyr1AD1I1I1RcpzR625rQ6HJKSuMB68hJ7FTY0ER9WHLJ6KbEga6G8CROk+vPAQl3ldPfA8NGnxM4KKkLBz/U2+IOekYz2QRRk=
  app: node-shopping-list-integration-tests
  on:
    repo: fishtailwrinkle/node-shopping-list-integration-tests
